version: '3'
services:
  cors_proxy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PROXY_TIMEOUT=30
      - PROXY_WHITE_LIST=example.com,allowed.com
      - PROXY_BLACK_LIST=blocked.com,forbidden.com