name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: 登录到 GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV} |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          REPO: '${{ github.repository }}'

      # Step 4: 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$OWNER_LC/cors-proxy:latest .

      # Step 5: 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/$OWNER_LC/cors-proxy:latest
